export const CurrenciesBlacklist = [
  'GBP', 'EUR', 'USDC', 'USDT', 'VAI',
  'SUN', 'BCHSV', 'TITAN', 'SAITAMA',
  'FREN', 'GHC', 'BCHABC', 'MEME',
  'PNT', 'YGG', 'HIT', 'GTC', 'XRP3S',
  'META', 'SIG', 'AAVE3S', 'SUSHI3S',
  'COCOS', 'FREE', 'BOND', 'MIR', 'DOGE3S',
  'BTT', 'BNB3S', 'DOT3S', 'LINK3S', 'MASK',
  'BDP', 'ACM', 'UNO', 'AVAX3L', 'BNB3L',
  'PLA', 'ATOM3S', 'ADA3S', 'ETH3L', 'DICE',
  'NEAR3L', 'LUN', 'BTC3S', 'VET3S', 'SOL3S',
  'MANA3L', 'DEXT', 'EASY', 'ACT', 'DOT3L',
  'XCH', 'SUB', 'SMT', 'CHAT', 'BTC3L',
  'UNI3S', 'BOX', 'MATIC3L', 'LINK3L',
  'MANA3S', 'UNI3L', 'AVAX3S', 'ZDC',
  'EOS3S', 'YOOSHI', 'EOS3S', 'WINGS',
  'BCN', 'SNGLS', 'HSR', 'XRP3L', 'FTM3L',
  'FTM3S', 'ETH3S', 'AXS3S', 'PHX', 'POE',
  'LTC3S', 'MATIC3S', 'AMP', 'BCH3S', 'DLT',
  'SAND3L', 'SALT', 'AAVE3L', 'STC', 'LUNA3L',
  'BRG', 'TUSD', 'BCPT', 'PAX', 'STRAT', 'DFI',
  'LUNA3S', 'HOT', 'EOS3L', 'TRADE', 'SAND3S',
  'DOGE3L', 'SOC', 'SOL3L', 'AXS3L', 'EDG',
  'SCRT', 'TNB', 'DAI', 'DGD', 'CREAM',
  'MBL', 'BCHA', 'SPICE', 'DOGE', 'ADA3L',
  'BCH3L', 'RCN', 'ADABEAR', 'LINKBEAR', 'IQ',
  'WOM', 'MTX', 'EDO', 'VET3L', 'OKB', 'HC',
  'FXS', 'CMT', 'AME', 'MFT', 'BZRX', 'VIBE',
  'AUDIO', 'BANANA', 'KEY', 'BNS', 'REVV',
  'ARK', 'XHV', 'BAAS', 'LUNA', 'ETC', 'DENT',
  'MDA', 'GN', 'RUNE', 'CNS', 'GOLD', 'POLX',
  'KIN', 'GET', 'SEELE', 'GRIN', 'NEAR3S',
  'ATOM3L', 'BLY', 'PPT', 'AKITA', 'ETHBEAR',
  'GXC', 'EM', 'TRU', 'HYDRO', 'XOR', 'TOP',
  'CVP', 'GLEEC', 'LTC3L', 'AUTO', 'FUN',
  'XDC', 'CHR', 'TRV', 'BOA', 'GNT', 'IOTA',
  'BNX', 'TOKE', 'LAMB', 'NFT', 'PNK', 'HAI',
  'PLU', 'ADK', 'JULD', 'XPR', 'DATX', 'ROOK',
  'POA', 'IPX', 'STPT', 'AERGO', 'AOA', 'UUU',
  'NU', 'VALUE', 'DORA', 'AE', 'UIP', 'MAN',
  'LEASH', 'BUX', 'STEEM', 'CLV', 'BTRST',
  'PSP', 'SUSHI3L', 'TKY', 'USDJ', 'NCASH',
  'CRU', 'BBTC', 'GM', 'KEEP', 'PLR', 'DYP',
  'ARPA', 'SUTER', 'FIRO', 'HGET', 'YLD', 'SXP',
  'MCB'
]